apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-5
    env: production
  name: pod-5
spec:
  containers:
  - image: nginx
    name: pod-5
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
