apiVersion: v1
kind: Pod
metadata:
  name: jay-pod-prod
spec:
  containers:
  - name: pod
    image: nginx
    resources:
      requests:
        memory: "50Mi"
        cpu: "0.1"
      limits:
        memory: "70Mi"
        cpu: "1"
    

